### ISSUE TITLE
Support flutter 3.22.x

### ISSUE THREAD

**Issue by Linij** [nghetien/tekflat_design#15]
Hello, your project is very cool and we hope to provide support for the new Flutter version.
For example, the version of the intl package is supported, and there are also some issues with the appearance and background color of the widgets.

**Comment by JJS-CN** [comment]
please update the intl package +1

**Comment by nghetien** [comment]
oke I got it

**Comment by nghetien** [comment]
I have been updated new version (1.6.12-flutter3.22)
